# -*- coding: utf-8 -*-
"""lab 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qGwy_19fGoSnMeZwstxijFkLZB28Ks9
"""

#23070521122,Rushi Parhad
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "WA_Fn-UseC_-Telco-Customer-Churn.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "blastchar/telco-customer-churn",
  file_path
)

print("Dataset loaded successfully. First 5 records:")
display(df.head())

import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd


file_path = "WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "blastchar/telco-customer-churn",
  file_path
)
print("DataFrame re-loaded for fresh preprocessing.")
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print("\nMissing values after converting TotalCharges:")
print(df.isnull().sum())
df.dropna(inplace=True)
df.drop('customerID', axis=1, inplace=True)
print("\nDataFrame info after handling TotalCharges and customerID:")
df.info()

categorical_cols_to_onehot = df.select_dtypes(include='object').columns.tolist()
if categorical_cols_to_onehot:
    df = pd.get_dummies(df, columns=categorical_cols_to_onehot, drop_first=True)
else:
    print("No object columns remaining for one-hot encoding.")

print("\nDataFrame head after one-hot encoding:")
display(df.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('Churn', axis=1)
y = df['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

scaled_numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

scaler = StandardScaler()
X_train[scaled_numerical_cols] = scaler.fit_transform(X_train[scaled_numerical_cols])
X_test[scaled_numerical_cols] = scaler.transform(X_test[scaled_numerical_cols])

print("\nScaled X_train head (numerical features):")
display(X_train[scaled_numerical_cols].head())

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=50,
    validation_split=0.2
    verbose=1
)
print("\nModel training complete.")

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype(int)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['No Churn', 'Churn'], yticklabels=['No Churn', 'Churn'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

print("\nClassification Report:")
print(classification_report(y_test, y_pred))